# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodeStrokeAlert' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for CodeStrokeAlert
    pod 'IQKeyboardManagerSwift'
    pod 'EVReflection/Alamofire'
    pod 'SVProgressHUD'
    pod 'OneSignal'
    pod 'PPBlinkID', '~> 4.0.0'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Toaster', '~> 2.0'
    pod 'SDWebImage', '~> 4.1’
    pod 'ASBPlayerScrubbing'
    pod 'AKMediaViewer'
end
